### ISSUE TITLE
Tab default name incrementation on click

### ISSUE THREAD

**Issue by firestar300** [n457/Uncolored#1] opened 2016-09-24 00:27 UTC
Hi,

When I close all tabs, and I click on the cross icon of the first tab called Unnamed-1, the name change to Unnamed-2, and Unnamed-3 etc....

![sans titre 2](https://cloud.githubusercontent.com/assets/2543936/18804664/5ba08f70-81fe-11e6-82ef-0ef8cfbaec1e.png)

**Comment by n457** [comment] 2016-09-24 13:56
Hi @firestar300, **thanks for your interest** in the application 👍 

**This is not a bug**, you're actually closing empty document tabs and (Un)colored **has always one tab opened**. So you're closing empty _Unnamed-13_, then (Un)colored **create a new empty document** _Unnamed-14_.

Maybe this mechanism isn't clear enough, I will replace _Unnamed-X_ by _Document-X_ for the next release

**Comment by n457** [comment] 2016-09-25 08:57
Default document tab name changed from _Unnamed-X_ to _Document-X_ for the next release

**Comment by firestar300** [comment] 2016-09-26 09:37
Ok, thanks n457.

**Closed as completed** 2016-09-27 21:30 UTC
Labels: improvement, not a bug, accepted, done. next release
